language: cpp
sudo: false

os: osx
osx_image: xcode7.3
compiler: gcc
env: CXX_=g++-5

# before_install:

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc5 gmp gsl boost; fi

before_script:
- export CXX=$CXX_
- $CXX --version
- make

script:
- make check

notifications:
  on_success: change
  on_failure: always

