# vim: set expandtab shiftwidth=2 softtabstop=2 :

language: cpp
sudo: required
service:
- docker

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env:
    - MY_NAME=travis-ci
    - MY_TARGET_DIST=ubuntu:16.04
    - MY_TARGET_MOUNT=/tell/pbkz

before_install:
- docker pull $MY_TARGET_DIST
- docker run --name $MY_NAME -v $TRAVIS_BUILD_DIR:$MY_TARGET_MOUNT -td $MY_TARGET_DIST /bin/bash

install:
- docker exec -ti $MY_NAME bash -c "apt update" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y build-essential git" > /dev/null
- docker exec -ti $MY_NAME bash -c "apt install -y libgmp-dev libmpfr-dev libgsl-dev libboost-all-dev" > /dev/null

before_script:
- docker exec -ti $MY_NAME bash -c "$CC --version"
- docker exec -ti $MY_NAME bash -c "$CXX --version"
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT && ll"
- docker exec -ti $MY_NAME bash -c "cd $MY_TARGET_MOUNT && make submods > /dev/null 2>&1 && touch submod.done"
- i=0; while [ ! -f submod.done ]; do sleep 300; echo $i; i=`expr $i + 1`; done

script:
- if which cppcheck; then find pbkzlib -iname '*.cpp' -exec cppcheck --enable=all --force -I `pwd`/pbkzlib -I `pwd`/prefix/include {} \; ; fi
- if which cpplint; then find pbkzlib -iname '*.cpp' -exec cpplint {} \; ; fi
- if [[ ! "$CPPCHECK_" == "1" ]]; then make; fi

notifications:
  on_success: change
  on_failure: always
