language: cpp
sudo: false

os: linux
compiler: gcc
env: CXX_=g++
addons:
  apt:
    sources:
    # - deadsnakes
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libgsl0-dev
cache:
  apt: true

# before_install:

# install:

before_script:
- export CXX=$CXX_
- $CXX --version
- make

script:
- make check

notifications:
  on_success: change
  on_failure: always

# vim : set expandtab :
