# vim: set expandtab :

language: cpp
sudo: required

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    # env: CXX_=g++
    addons:
      apt:
        sources:
        # - deadsnakes
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - libgmp-dev
        - libgsl0-dev
        - libboost-all-dev
        - cppcheck
    cache:
      apt: true
  - os: osx
    osx_image: xcode8
    compiler: gcc
    env: CXX_=g++

# before_install:

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl gmp cppcheck; fi

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=$CXX_; fi
- $CXX --version
- make submods > /dev/null 2>&1 && touch submod.done &
- i=0; while [ ! -f submod.done ]; do sleep 240; echo $i; i=`expr $i + 1`; done

script:
- if which cppcheck; then find pbkzlib -iname '*.cpp' -exec cppcheck --force -I `pwd`/pbkzlib -I `pwd`/prefix/include {} \; ; fi
- make

notifications:
  on_success: change
  on_failure: always
