# vim: set expandtab shiftwidth=2 softtabstop=2 :

language: cpp
sudo: required
service:
- docker

os: linux
dist: trusty
compiler: gcc
env:
  - MY_NAME=travis-ci
  - MY_GIT_REPO=/tell/pbkz

before_install:
- docker pull ubuntu:16.04
- docker run --name $MY_NAME -v $TRAVIS_BUILD_DIR:$MY_GIT_REPO -td ubuntu:16.04 /bin/bash

install:
- docker exec -ti travis-ci bash -c "apt update"
- docker exec -ti travis-ci bash -c "apt install -y build-essential"
- docker exec -ti travis-ci bash -c "apt install -y libgmp-dev libmpfr-dev libgsl-dev libboost-all-dev"

before_script:
- $CC --version
- $CXX --version
- make submods > /dev/null 2>&1 && touch submod.done &
- i=0; while [ ! -f submod.done ]; do sleep 300; echo $i; i=`expr $i + 1`; done

script:
- if which cppcheck; then find pbkzlib -iname '*.cpp' -exec cppcheck --enable=all --force -I `pwd`/pbkzlib -I `pwd`/prefix/include {} \; ; fi
- if which cpplint; then find pbkzlib -iname '*.cpp' -exec cpplint {} \; ; fi
- if [[ ! "$CPPCHECK_" == "1" ]]; then make; fi

notifications:
  on_success: change
  on_failure: always
