# vim: set expandtab shiftwidth=2 softtabstop=2 :

language: cpp
sudo: required

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env: CXX_=g++-5
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - g++-5
        - libgmp-dev
        - libmpfr-dev
        - libgsl0-dev
        - libboost-all-dev
    cache:
      apt: true
  - os: linux
    dist: trusty
    compiler: gcc
    env: CXX_=g++-5
    env: CPPCHECK_=1
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - g++-5
        - libgmp-dev
        - libmpfr-dev
        - libgsl0-dev
        - libboost-all-dev
        - cppcheck
        - python3
        - python3-pip
    cache:
      apt: true
  - os: osx
    osx_image: xcode8.3
    compiler: gcc
    env: CXX_=g++

# before_install:

install:
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install cpplint; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list gsl &>/dev/null || brew install gsl; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list mpfr &>/dev/null || brew install mpfr; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list gmp &>/dev/null || brew install gmp; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list cppcheck &>/dev/null || brew install cppcheck; fi

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=$CXX_; fi
- $CXX --version
- make submods > /dev/null 2>&1 && touch submod.done &
- i=0; while [ ! -f submod.done ]; do sleep 300; echo $i; i=`expr $i + 1`; done

script:
- if which cppcheck; then find pbkzlib -iname '*.cpp' -exec cppcheck --enable=all --force -I `pwd`/pbkzlib -I `pwd`/prefix/include {} \; ; fi
- if which cpplint; then find pbkzlib -iname '*.cpp' -exec cpplint {} \; ; fi
- make

notifications:
  on_success: change
  on_failure: always
