language: cpp
sudo: required

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env: CXX_=g++-4.8
    addons:
      apt:
        sources:
        # - deadsnakes
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - libgmp-dev
        - libgsl0-dev
        - libboost1.55-dev
    cache:
      apt: true
  - os: osx
    osx_image: xcode7.3
    compiler: gcc
    env: CXX_=g++

# before_install:

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl gmp boost; fi

before_script:
- export CXX=$CXX_
- $CXX --version
- make submods

script:
- make

notifications:
  on_success: change
  on_failure: always

# vim: set expandtab :
